name = "PackFrameworkerExample"
author = "Den4enko"
version = "v4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bba5d96af43613d7c2cc5c1db9fa9b9858720b540c80f76af5ac1e8fe580f9d8"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
