name = "PackFramework"
author = "Den4enko"
version = "dev-6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bb12a95aa23bae60eacdfccee820375f8924a6ed583d275122c7fb2e2344f33f"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.238"

[options]
no-internal-hashes = true
