name = "PackFramework"
author = "Den4enko"
version = "dev-6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fb939b5ec56c3ed80c4789bd5535cbfbca8eee8c4f01497699192fe94facbe84"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.238"

[options]
no-internal-hashes = true
