name = "PackFramework"
author = "Den4enko"
version = "dev-6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ec413644628454c4f36597157a5f3188b0011cb89fa94da60d3ea5b3925354f4"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.238"

[options]
no-internal-hashes = true
